import type { Metadata } from "next";
import { inter } from './lib/fonts';
import "./global.css";
<<<<<<< HEAD
import Navbar from "@/app/ui/Navbar";
import Footer from "@/app/ui/Footer";
=======
import Providers from "./providers";
>>>>>>> bd6a292 (WIP: local changes before pulling)


export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
    </head>
      <body className={`${inter.className} antialiased`}>
<<<<<<< HEAD
        <Navbar />
        {children}
        <Footer />
=======
        <Providers>{children}</Providers>
>>>>>>> bd6a292 (WIP: local changes before pulling)
      </body>
    </html>
  );
}
